# -*- coding: utf-8 -*-
"""project_gpe2d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16d7PdPOvIYQ5VDBYzVskNcEqItHrsuEB
"""

import time
import csv
import numpy as np
import matplotlib.pyplot as plt

def build_grid(L=10.0, nx=64, ny=64):
    """Build 2D periodic grid on [-L,L]^2."""
    x = np.linspace(-L, L, nx, endpoint=False)
    y = np.linspace(-L, L, ny, endpoint=False)
    dx = x[1] - x[0]
    dy = y[1] - y[0]
    X, Y = np.meshgrid(x, y, indexing="ij")
    return x, y, X, Y, dx, dy


def initial_wavepacket(x, y,
                       x0=-3.0, y0=0.0,
                       sigma=1.0,
                       kx0=2.0, ky0=0.0):
    """
    Normalized 2D Gaussian wavepacket
        psi0 ~ exp(-((x-x0)^2+(y-y0)^2)/(2 sigma^2)) * exp(i (k·x)).
    """
    X, Y = np.meshgrid(x, y, indexing="ij")
    gauss = np.exp(-((X - x0) ** 2 + (Y - y0) ** 2) / (2.0 * sigma ** 2))
    phase = np.exp(1j * (kx0 * X + ky0 * Y))
    psi0 = gauss * phase

    dx = x[1] - x[0]
    dy = y[1] - y[0]
    norm = np.sqrt(np.sum(np.abs(psi0) ** 2) * dx * dy)
    return psi0 / norm


def compute_mass(psi, dx, dy):
    """Discrete mass M = sum |psi|^2 dx dy."""
    return np.sum(np.abs(psi) ** 2) * dx * dy


def compute_energy(psi, V, g, dx, dy, KX, KY):
    """
    Discrete energy:
        E = ∫ [ 1/2|∇psi|^2 + V|psi|^2 + g/2 |psi|^4 ] dx dy
    uses spectral differentiation for gradients.
    """
    psi_hat = np.fft.fft2(psi)
    gradx_hat = 1j * KX * psi_hat
    grady_hat = 1j * KY * psi_hat
    gradx = np.fft.ifft2(gradx_hat)
    grady = np.fft.ifft2(grady_hat)

    kinetic = 0.5 * (np.abs(gradx) ** 2 + np.abs(grady) ** 2)
    density = np.abs(psi) ** 2
    potential = V * density
    nonlinear = 0.5 * g * density ** 2

    return np.real(np.sum(kinetic + potential + nonlinear) * dx * dy)

def build_spectral_operators(nx, ny, dx, dy):
    """Precompute Fourier wavenumbers and KX, KY, K2."""
    kx = 2.0 * np.pi * np.fft.fftfreq(nx, d=dx)
    ky = 2.0 * np.pi * np.fft.fftfreq(ny, d=dy)
    KX, KY = np.meshgrid(kx, ky, indexing="ij")
    K2 = KX ** 2 + KY ** 2
    return KX, KY, K2


def splitstep_gpe_2d(psi0, V, g, dt, T, x, y, KX, KY, K2):
    """
    2D split-step (Strang) solver for
        i psi_t = -1/2 Δ psi + V psi + g |psi|^2 psi
    with periodic BCs.

    Inputs:
        psi0 : initial condition on grid (nx,ny)
        V    : potential on grid (nx,ny)
        g    : nonlinearity parameter
        dt   : time step
        T    : final time
        x,y  : 1D grids
        KX,KY,K2 : spectral operators

    Outputs:
        psiT      : solution at time T
        t_hist    : array of times
        mass_hist : mass at each time step
        energy_hist : energy at each time step
    """
    nx = len(x)
    ny = len(y)
    dx = x[1] - x[0]
    dy = y[1] - y[0]

    n_steps = int(round(T / dt))
    psi = psi0.copy()

    # Precompute half-step kinetic propagator (simple optimization)
    expK_half = np.exp(-1j * 0.5 * dt * 0.5 * K2)

    # Diagnostics history
    t_hist = np.linspace(0.0, T, n_steps + 1)
    mass_hist = np.zeros(n_steps + 1, dtype=float)
    energy_hist = np.zeros(n_steps + 1, dtype=float)

    mass_hist[0] = compute_mass(psi, dx, dy)
    energy_hist[0] = compute_energy(psi, V, g, dx, dy, KX, KY)

    for n in range(1, n_steps + 1):
        # half-step kinetic in Fourier
        psi_hat = np.fft.fft2(psi)
        psi_hat *= expK_half
        psi = np.fft.ifft2(psi_hat)

        # full-step potential + nonlinearity in real space
        density = np.abs(psi) ** 2
        expV = np.exp(-1j * dt * (V + g * density))
        psi *= expV

        # half-step kinetic again
        psi_hat = np.fft.fft2(psi)
        psi_hat *= expK_half
        psi = np.fft.ifft2(psi_hat)

        # invariants
        mass_hist[n] = compute_mass(psi, dx, dy)
        energy_hist[n] = compute_energy(psi, V, g, dx, dy, KX, KY)

    return psi, t_hist, mass_hist, energy_hist

# Commented out IPython magic to ensure Python compatibility.
def run_experiment():
    # ----- configuration -----
    L = 10.0
    nx = ny = 64
    omega = 0.2           # harmonic trap frequency
    T = 2.0
    dt_list = [0.01, 0.04, 0.08]
    regimes = [("linear", 0.0), ("nonlinear", 50.0)]

    # ----- grid and potential -----
    x, y, X, Y, dx, dy = build_grid(L=L, nx=nx, ny=ny)
    V = 0.5 * omega ** 2 * (X ** 2 + Y ** 2)

    # ----- spectral operators (reused for all runs) -----
    KX, KY, K2 = build_spectral_operators(nx, ny, dx, dy)

    # ----- initial data -----
    psi0 = initial_wavepacket(x, y)
    M0 = compute_mass(psi0, dx, dy)
    print("Initial mass M0 = %.16f" % M0)

    # store results
    results = []

    # ----- loop over regimes and dt -----
    for regime_name, g in regimes:
        print("\nRegime: %s (g = %.3f)" % (regime_name, g))
        for dt in dt_list:
            t_start = time.perf_counter()

            psiT, t_hist, mass_hist, energy_hist = splitstep_gpe_2d(
                psi0, V, g, dt, T, x, y, KX, KY, K2
            )

            cpu = time.perf_counter() - t_start
            max_mass_err = float(np.max(np.abs(mass_hist - M0)))
            E0 = float(energy_hist[0])
            ET = float(energy_hist[-1])

            results.append(
                {
                    "regime": regime_name,
                    "g": g,
                    "dt": dt,
                    "cpu": cpu,
                    "M_final": float(mass_hist[-1]),
                    "max_mass_err": max_mass_err,
                    "E0": E0,
                    "ET": ET,
                    "E_diff": abs(ET - E0),
                }
            )

            print(
                "  dt = %.3f, steps = %4d, cpu = %.3fs, "
                "max |M(t)-M0| = %.3e, |E(T)-E(0)| = %.3e"
#                 % (dt, len(t_hist) - 1, cpu, max_mass_err, abs(ET - E0))
            )

            # save plots for reference dt (here: dt_list[0])
            if abs(dt - dt_list[0]) < 1e-12:
                save_plots_for_run(regime_name, dt, x, y,
                                   psiT, t_hist, mass_hist, energy_hist)

    # ----- write summary files -----
    write_summary(results)
    print("\nSummary written to results_summary.txt and results_summary.csv")

def save_plots_for_run(regime_name, dt, x, y, psiT, t_hist, mass_hist, energy_hist):
    """Save density, mass, and energy plots for a single run (one regime, one dt)."""
    # density at final time
    fname_density = f"density_{regime_name}_dt{dt:.2f}.png"
    plt.figure(figsize=(5, 4))
    plt.pcolormesh(x, y, np.abs(psiT) ** 2, shading="auto")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title(r"|$\psi(x,y,T)|^2$, %s, dt=%.2f" % (regime_name, dt))
    plt.colorbar()
    plt.tight_layout()
    plt.savefig(fname_density, dpi=150)
    plt.close()

    # mass vs time
    fname_mass = f"mass_{regime_name}_dt{dt:.2f}.png"
    plt.figure()
    plt.plot(t_hist, mass_hist)
    plt.xlabel("t")
    plt.ylabel("mass M(t)")
    plt.title("Mass vs time, %s, dt=%.2f" % (regime_name, dt))
    plt.tight_layout()
    plt.savefig(fname_mass, dpi=150)
    plt.close()

    # energy vs time
    fname_energy = f"energy_{regime_name}_dt{dt:.2f}.png"
    plt.figure()
    plt.plot(t_hist, energy_hist)
    plt.xlabel("t")
    plt.ylabel("Energy E(t)")
    plt.title("Energy vs time, %s, dt=%.2f" % (regime_name, dt))
    plt.tight_layout()
    plt.savefig(fname_energy, dpi=150)
    plt.close()

# Commented out IPython magic to ensure Python compatibility.
def write_summary(results):
    """Write plain-text and CSV summary of all runs."""
    # text file
    with open("results_summary.txt", "w") as f:
        f.write("Regime   g      dt      CPU[s]   M_final        "
                "max|M-M0|      E(0)          E(T)          |E(T)-E(0)|\n")
        for r in results:
            f.write(
                "%-8s %6.2f %7.3f %8.3f %13.8f %11.3e %13.8f %13.8f %13.8f\n"
#                 % (
                    r["regime"],
                    r["g"],
                    r["dt"],
                    r["cpu"],
                    r["M_final"],
                    r["max_mass_err"],
                    r["E0"],
                    r["ET"],
                    r["E_diff"],
                )
            )

    # CSV file
    with open("results_summary.csv", "w", newline="") as fcsv:
        writer = csv.writer(fcsv)
        writer.writerow(
            ["regime", "g", "dt", "cpu_s", "M_final",
             "max_mass_err", "E0", "ET", "E_diff"]
        )
        for r in results:
            writer.writerow(
                [
                    r["regime"], r["g"], r["dt"], r["cpu"],
                    r["M_final"], r["max_mass_err"],
                    r["E0"], r["ET"], r["E_diff"],
                ]
            )

if __name__ == "__main__":
    run_experiment()