# -*- coding: utf-8 -*-
"""project_gpe2d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16d7PdPOvIYQ5VDBYzVskNcEqItHrsuEB
"""

# Commented out IPython magic to ensure Python compatibility.
import time
import csv
import os
import platform
import numpy as np
import matplotlib.pyplot as plt
def build_grid(L=10.0, nx=64, ny=64):
    """Build 2D periodic grid on [-L,L]^2."""
    x = np.linspace(-L, L, nx, endpoint=False)
    y = np.linspace(-L, L, ny, endpoint=False)
    dx = x[1] - x[0]
    dy = y[1] - y[0]
    X, Y = np.meshgrid(x, y, indexing="ij")
    return x, y, X, Y, dx, dy
def initial_wavepacket(x, y,
                       x0=-3.0, y0=0.0,
                       sigma=1.0,
                       kx0=2.0, ky0=0.0):

    X, Y = np.meshgrid(x, y, indexing="ij")
    gauss = np.exp(-((X - x0) ** 2 + (Y - y0) ** 2) / (2.0 * sigma ** 2))
    phase = np.exp(1j * (kx0 * X + ky0 * Y))
    psi0 = gauss * phase
    dx = x[1] - x[0]
    dy = y[1] - y[0]
    norm = np.sqrt(np.sum(np.abs(psi0) ** 2) * dx * dy)
    return psi0 / norm


def compute_mass(psi, dx, dy):
    return np.sum(np.abs(psi) ** 2) * dx * dy


def compute_energy(psi, V, g, dx, dy, KX, KY):
    psi_hat = np.fft.fft2(psi)
    gradx_hat = 1j * KX * psi_hat
    grady_hat = 1j * KY * psi_hat
    gradx = np.fft.ifft2(gradx_hat)
    grady = np.fft.ifft2(grady_hat)

    kinetic = 0.5 * (np.abs(gradx) ** 2 + np.abs(grady) ** 2)
    density = np.abs(psi) ** 2
    potential = V * density
    nonlinear = 0.5 * g * density ** 2

    return np.real(np.sum(kinetic + potential + nonlinear) * dx * dy)
def build_spectral_operators(nx, ny, dx, dy):
    """Precompute Fourier wavenumbers and KX, KY, K2."""
    kx = 2.0 * np.pi * np.fft.fftfreq(nx, d=dx)
    ky = 2.0 * np.pi * np.fft.fftfreq(ny, d=dy)
    KX, KY = np.meshgrid(kx, ky, indexing="ij")
    K2 = KX ** 2 + KY ** 2
    return KX, KY, K2
def splitstep_gpe_2d(psi0, V, g, dt, T, x, y, KX, KY, K2):
    nx = len(x)
    ny = len(y)
    dx = x[1] - x[0]
    dy = y[1] - y[0]

    n_steps = int(round(T / dt))
    psi = psi0.copy()
    expK_half = np.exp(-1j * 0.5 * dt * 0.5 * K2)
    t_hist = np.linspace(0.0, T, n_steps + 1)
    mass_hist = np.zeros(n_steps + 1, dtype=float)
    energy_hist = np.zeros(n_steps + 1, dtype=float)

    mass_hist[0] = compute_mass(psi, dx, dy)
    energy_hist[0] = compute_energy(psi, V, g, dx, dy, KX, KY)

    for n in range(1, n_steps + 1):
        psi_hat = np.fft.fft2(psi)
        psi_hat *= expK_half
        psi = np.fft.ifft2(psi_hat)
        density = np.abs(psi) ** 2
        expV = np.exp(-1j * dt * (V + g * density))
        psi *= expV
        psi_hat = np.fft.fft2(psi)
        psi_hat *= expK_half
        psi = np.fft.ifft2(psi_hat)
        mass_hist[n] = compute_mass(psi, dx, dy)
        energy_hist[n] = compute_energy(psi, V, g, dx, dy, KX, KY)
    return psi, t_hist, mass_hist, energy_hist

def compute_speedup(results):
    """Add 'speedup' field to each result, relative to smallest dt for that regime."""
    baseline_cpu = {}
    baseline_dt = {}

    for r in results:
        reg = r["regime"]
        dt = r["dt"]
        if reg not in baseline_dt or dt < baseline_dt[reg]:
            baseline_dt[reg] = dt
            baseline_cpu[reg] = r["cpu"]

    for r in results:
        reg = r["regime"]
        cpu_ref = baseline_cpu[reg]
        r["speedup"] = cpu_ref / r["cpu"] if r["cpu"] > 0 else float("nan")

def plot_speedup(results):
    """Speedup vs dt for each regime."""
    regimes = sorted(set(r["regime"] for r in results))
    plt.figure()
    for reg in regimes:
        rs = sorted([r for r in results if r["regime"] == reg],
                    key=lambda z: z["dt"])
        dts = [r["dt"] for r in rs]
        spd = [r["speedup"] for r in rs]
        plt.plot(dts, spd, marker="o", label=reg)
    plt.xlabel(r"time step $\Delta t$")
    plt.ylabel("speedup vs smallest dt")
    plt.title("Speedup vs time step")
    plt.legend()
    plt.tight_layout()
    plt.savefig("speedup_vs_dt.png", dpi=150)
    plt.close()

def plot_error_maps(final_states, x, y):
    """
    Absolute error maps between dt=0.08 and dt=0.01
    for linear and nonlinear regimes.
    """
    for regime in ["linear", "nonlinear"]:
        key_fine = (regime, 0.01)
        key_coarse = (regime, 0.08)
        if key_fine not in final_states or key_coarse not in final_states:
            continue
        psi_ref = final_states[key_fine]
        psi_coarse = final_states[key_coarse]
        err = np.abs(psi_coarse - psi_ref)

        fname = f"error_{regime}_dt0.08_vs_dt0.01.png"
        plt.figure(figsize=(5, 4))
        plt.pcolormesh(x, y, err, shading="auto")
        plt.xlabel("x")
        plt.ylabel("y")
        plt.title(
            rf"Absolute error $|\psi_{{\Delta t=0.08}}-\psi_{{\Delta t=0.01}}|$, {regime}"
        )
        plt.colorbar()
        plt.tight_layout()
        plt.savefig(fname, dpi=150)
        plt.close()


def run_verification_tests(results):
    print("\nVerification tests:")
    tests = [
        ("linear", 0.0, 0.01, 1e-10, 1e-6),
        ("nonlinear", 50.0, 0.01, 1e-10, 1e-3),
    ]
    for reg, g, dt, mass_tol, E_tol in tests:
        r = next(
            (rr for rr in results
             if rr["regime"] == reg and abs(rr["dt"] - dt) < 1e-12),
            None,
        )
        if r is None:
            print(f"  [FAIL] No result for regime={reg}, dt={dt}")
            continue
        mm = r["max_mass_err"]
        de = r["E_diff"]
        passed = (mm <= mass_tol) and (de <= E_tol)
        status = "PASS" if passed else "FAIL"
        print(
            f"  {reg:9s}, dt={dt:.2f}: "
            f"max|M-M0|={mm:.3e}, |E(T)-E(0)|={de:.3e} -> {status}"
        )


def save_plots_for_run(regime_name, dt, x, y, psiT, t_hist, mass_hist, energy_hist):
    # density at final time
    fname_density = f"density_{regime_name}_dt{dt:.2f}.png"
    plt.figure(figsize=(5, 4))
    plt.pcolormesh(x, y, np.abs(psiT) ** 2, shading="auto")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title(r"|$\psi(x,y,T)|^2$, %s, dt=%.2f" % (regime_name, dt))
    plt.colorbar()
    plt.tight_layout()
    plt.savefig(fname_density, dpi=150)
    plt.close()

    # mass vs time
    fname_mass = f"mass_{regime_name}_dt{dt:.2f}.png"
    plt.figure()
    plt.plot(t_hist, mass_hist)
    plt.xlabel("t")
    plt.ylabel("mass M(t)")
    plt.title("Mass vs time, %s, dt=%.2f" % (regime_name, dt))
    plt.tight_layout()
    plt.savefig(fname_mass, dpi=150)
    plt.close()

    # energy vs time
    fname_energy = f"energy_{regime_name}_dt{dt:.2f}.png"
    plt.figure()
    plt.plot(t_hist, energy_hist)
    plt.xlabel("t")
    plt.ylabel("Energy E(t)")
    plt.title("Energy vs time, %s, dt=%.2f" % (regime_name, dt))
    plt.tight_layout()
    plt.savefig(fname_energy, dpi=150)
    plt.close()


def write_summary(results):
    # text file
    with open("results_summary.txt", "w") as f:
        f.write(
            "Regime   g      dt      CPU[s]   speedup   M_final        "
            "max|M-M0|      E(0)          E(T)          |E(T)-E(0)|\n"
        )
        for r in results:
            f.write(
                "%-8s %6.2f %7.3f %8.3f %9.3f %13.8f %11.3e %13.8f %13.8f %13.8f\n"
#                 % (
                    r["regime"],
                    r["g"],
                    r["dt"],
                    r["cpu"],
                    r["speedup"],
                    r["M_final"],
                    r["max_mass_err"],
                    r["E0"],
                    r["ET"],
                    r["E_diff"],
                )
            )

    # CSV file
    with open("results_summary.csv", "w", newline="") as fcsv:
        writer = csv.writer(fcsv)
        writer.writerow(
            [
                "regime",
                "g",
                "dt",
                "cpu_s",
                "speedup",
                "M_final",
                "max_mass_err",
                "E0",
                "ET",
                "E_diff",
            ]
        )
        for r in results:
            writer.writerow(
                [
                    r["regime"],
                    r["g"],
                    r["dt"],
                    r["cpu"],
                    r["speedup"],
                    r["M_final"],
                    r["max_mass_err"],
                    r["E0"],
                    r["ET"],
                    r["E_diff"],
                ]
            )


def run_experiment():
    L = 10.0
    nx = ny = 64
    omega = 0.2           # harmonic trap frequency
    T = 2.0
    dt_list = [0.01, 0.04, 0.08]
    regimes = [("linear", 0.0), ("nonlinear", 50.0)]
    print("CPU logical cores:", os.cpu_count())
    x, y, X, Y, dx, dy = build_grid(L=L, nx=nx, ny=ny)
    V = 0.5 * omega ** 2 * (X ** 2 + Y ** 2)
    KX, KY, K2 = build_spectral_operators(nx, ny, dx, dy)
    psi0 = initial_wavepacket(x, y)
    M0 = compute_mass(psi0, dx, dy)
    print("Initial mass M0 = %.16f" % M0)
    results = []
    final_states = {}
    for regime_name, g in regimes:
        print("\nRegime: %s (g = %.3f)" % (regime_name, g))
        for dt in dt_list:
            t_start = time.perf_counter()

            psiT, t_hist, mass_hist, energy_hist = splitstep_gpe_2d(
                psi0, V, g, dt, T, x, y, KX, KY, K2
            )

            cpu = time.perf_counter() - t_start
            max_mass_err = float(np.max(np.abs(mass_hist - M0)))
            E0 = float(energy_hist[0])
            ET = float(energy_hist[-1])

            results.append(
                {
                    "regime": regime_name,
                    "g": g,
                    "dt": dt,
                    "cpu": cpu,
                    "M_final": float(mass_hist[-1]),
                    "max_mass_err": max_mass_err,
                    "E0": E0,
                    "ET": ET,
                    "E_diff": abs(ET - E0),
                }
            )

            final_states[(regime_name, dt)] = psiT

            print(
                "  dt = %.3f, steps = %4d, cpu = %.3fs, "
                "max |M(t)-M0| = %.3e, |E(T)-E(0)| = %.3e"
#                 % (dt, len(t_hist) - 1, cpu, max_mass_err, abs(ET - E0))
            )

            if abs(dt - dt_list[0]) < 1e-12:
                save_plots_for_run(
                    regime_name, dt, x, y, psiT, t_hist, mass_hist, energy_hist
                )

    compute_speedup(results)
    run_verification_tests(results)
    write_summary(results)
    plot_speedup(results)
    plot_error_maps(final_states, x, y)

    print("\nSummary written to results_summary.txt and results_summary.csv")
    print("Additional plots: speedup_vs_dt.png, error_*_dt0.08_vs_dt0.01.png")



if __name__ == "__main__":
    run_experiment()